from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

_ROUTE_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]*")
_MARKER = ".finlaws-pagefind-generated"


def stage_partition(site_root: Path, staging_root: Path, routes: list[str]) -> int:
    """Hard-link one partition's law HTML into an isolated Pagefind input tree."""
    site_root = site_root.resolve()
    staging_root = staging_root.resolve()
    staging_root.mkdir(parents=True, exist_ok=True)
    count = 0
    for route in routes:
        if not _ROUTE_PATTERN.fullmatch(route):
            raise ValueError(f"invalid law route: {route!r}")
        source_dir = (site_root / "law" / route).resolve()
        if not source_dir.is_relative_to(site_root / "law") or not source_dir.is_dir():
            raise FileNotFoundError(f"missing law route: {route}")
        for source in sorted(source_dir.rglob("*.html")):
            if b"data-pagefind-body" not in source.read_bytes():
                continue
            relative = source.relative_to(site_root)
            target = staging_root / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            try:
                os.link(source, target)
            except OSError:
                shutil.copyfile(source, target)
            count += 1
    return count


def _prepare_output(site_root: Path, output_root: Path) -> None:
    if output_root == site_root or not output_root.is_relative_to(site_root):
        raise ValueError("Pagefind output must be a child of the built site")
    marker = output_root / _MARKER
    if output_root.exists():
        if not marker.is_file():
            raise RuntimeError(f"refusing to replace unmarked Pagefind output: {output_root}")
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True)
    (output_root / _MARKER).write_text("generated by scripts/build_search_indexes.py\n", encoding="utf-8")


def build_partitioned_indexes(
    site_root: Path,
    source_manifest: Path,
    output_root: Path,
    pagefind_command: list[str],
) -> dict[str, object]:
    """Build one CJK Pagefind index per legal category and emit a browser manifest."""
    site_root = site_root.resolve()
    source_manifest = source_manifest.resolve()
    output_root = output_root.resolve()
    if not site_root.is_dir():
        raise FileNotFoundError(f"missing built site: {site_root}")
    if not pagefind_command:
        raise ValueError("pagefind command must not be empty")
    source = json.loads(source_manifest.read_text(encoding="utf-8"))
    base_path = source.get("base_path")
    partitions = source.get("partitions")
    if not isinstance(base_path, str) or not base_path.startswith("/") or not base_path.endswith("/"):
        raise ValueError("invalid base_path in search partition manifest")
    if not isinstance(partitions, list) or not partitions:
        raise ValueError("search partition manifest has no partitions")

    _prepare_output(site_root, output_root)
    environment = os.environ.copy()
    environment["RAYON_NUM_THREADS"] = "1"
    built: list[dict[str, object]] = []
    indexed_pages = 0
    staging_parent = site_root.parent

    for partition in partitions:
        if not isinstance(partition, dict):
            raise ValueError("invalid search partition entry")
        name = partition.get("name")
        category = partition.get("category")
        routes = partition.get("routes")
        if not isinstance(name, str) or not _ROUTE_PATTERN.fullmatch(name):
            raise ValueError(f"invalid partition name: {name!r}")
        if not isinstance(category, str) or not isinstance(routes, list) or not all(isinstance(route, str) for route in routes):
            raise ValueError(f"invalid partition payload: {name}")
        if not routes:
            continue
        with tempfile.TemporaryDirectory(prefix=f".pagefind-{name}-", dir=staging_parent) as temporary:
            staging_root = Path(temporary)
            page_count = stage_partition(site_root, staging_root, routes)
            partition_output = output_root / name
            subprocess.run(
                [
                    *pagefind_command,
                    "--site",
                    str(staging_root),
                    "--output-path",
                    str(partition_output),
                    "--force-language",
                    "ja",
                    "--quiet",
                ],
                check=True,
                env=environment,
            )
        if not (partition_output / "pagefind.js").is_file():
            raise RuntimeError(f"Pagefind did not create pagefind.js for partition {name}")
        indexed_pages += page_count
        built.append(
            {
                "name": name,
                "category": category,
                "bundle": f"{name}/",
                "pages": page_count,
            }
        )

    browser_manifest = {
        "base_path": base_path,
        "partitions": built,
    }
    (output_root / "manifest.json").write_text(
        json.dumps(browser_manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {
        "base_path": base_path,
        "partitions": len(built),
        "indexed_pages": indexed_pages,
        "output": str(output_root),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build memory-bounded partitioned Pagefind indexes")
    parser.add_argument("--site", type=Path, default=Path("site"))
    parser.add_argument("--manifest", type=Path, default=Path("site/search-partitions.json"))
    parser.add_argument("--output", type=Path, default=Path("site/pagefind"))
    parser.add_argument("--pagefind", default="node_modules/.bin/pagefind")
    arguments = parser.parse_args()
    report = build_partitioned_indexes(
        arguments.site,
        arguments.manifest,
        arguments.output,
        [arguments.pagefind],
    )
    print(json.dumps(report, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
